### ISSUE TITLE
Update SEO and share card 

### ISSUE THREAD

**Issue by crisdobb** [cleanlab/cleanlab-docs#10]
Title: Open-Source Documentation | Cleanlab
Description: Get started with Cleanlab Open-Source, learn about capabilities, and follow tutorials to improve your own Data and Models.
![social-share-card-docs-open-source](https://github.com/cleanlab/cleanlab-docs/assets/148264362/74f1d220-ec3e-412d-8f09-8dcf130ef5e8)

**Comment by crisdobb** [comment]
@anishathalye can you add Riddhi here or help me with this?

**Comment by anishathalye** [comment]
Done, see https://github.com/cleanlab/cleanlab/commit/21c46c9cea788d86c6112b2f7642a8835eec55ce and https://github.com/cleanlab/assets/commit/54ffe9bdaa1f0f5e0497855d88901831e0a603cb.
